### ISSUE TITLE
( ! ) Notice: Undefined variable: cpunum_cores in php/system.php on line 141

### ISSUE THREAD

**Issue by xoco70** [fuzzymannerz/swmp#1]
Hi, 

I just installed the software, I get it working, but I have this notice, is it ok???

I will hide notice messages, but I wanted to tell you !

**Comment by fuzzymannerz** [comment]
Thanks for pointing that out! I've removed the line from _system.php_.
You can either download the new system.php or just edit your version and remove line 141 completely.
`    'num_cores'  => $cpunum_cores,`
