### ISSUE TITLE
Option to disable CPU cache size check

### ISSUE THREAD

**Issue by djbeadle** [fuzzymannerz/swmp#11]
Every time I refresh the page I get the error in red at the top "CPU cache size could not be determined: output could not be parsed"

This seems to be because on my Raspberry Pi (Raspbian Jessie, 8.0) the file /proc/cpuinfo has no field named "cache size" or "l2 cache". The function that throws the error is linked [here](https://github.com/fuzzymannerz/swmp/blob/ca13256f3cecc80035d9b0c06c23dc77d96f3de3/php/system.php#L210). 

Is there a better way to silence this besides simply commenting it out?

**Comment by fuzzymannerz** [comment]
If commenting it out works fine then you may as well do that. :P
I didn't make the error checks so maybe see what @Mikescher has to say on this?

**Comment by Mikescher** [comment]
The correct way would probably be to introduce options to hide individual properties - but yeah commenting it out sounds reasonable :D
