### ISSUE TITLE
Convert into class and support composer

### ISSUE THREAD

**Issue by daison12006013** [fuzzymannerz/swmp#3]
Hey @fuzzymannerz, this looks awesome, can I re-design the php files into class based? so we could re-use some functions for an instantiations.

**Comment by fuzzymannerz** [comment]
Thanks for your kind words!
I'm not much of a PHP developer and pulled most of the PHP scripts from the "eZ Server Monitor Web" project (See credits) and I know it could so with some re-jiggling so feel free to improve it or make it easier to use or whatever, if you feel to submit a pull request also, I'll have a look and merge if it can help others in making this project better in the long run. :)
