### ISSUE TITLE
Install script support for rpm based systems

### ISSUE THREAD

**Issue by Aftermath** [fuzzymannerz/swmp#8]
Are there plans for this?
For example, compatibility with rpm, yum/dnf (RHEL/Fedora)?
I had started to work on this myself, but I noticed that the install script was not included in the repository.

**Comment by fuzzymannerz** [comment]
Hi, there aren't any plans currently and I am rather busy with other things at the moment to get to this but if you wish you can continue to work on it and providing it all works I'll merge it in.

The current basic install script is here:
https://getswmp.thefuzz.xyz/install.sh

All it really does is check for the relevant software packages (_git_ and _apache2-utils_) and puts things in the right places.

**Comment by Aftermath** [comment]
Alright,
I'll take a look at this soon.

**Comment by fuzzymannerz** [comment]
Just a heads up that I am now working on this and I will release the updated installer script as soon as it's done. I will comment and close this issue once complete.
