### ISSUE TITLE
Install script support for Archlinux

### ISSUE THREAD

**Issue by XenGi** [fuzzymannerz/swmp#9]
The install script only works for debian/ubuntu and should be adapted to other distros. I will try to contribute  the Archlinux part when I find the time for it.

**Comment by XenGi** [comment]
I'm running swmp under Archlinux with php-fpm 7.0.14 and nginx 1.10.2 and I get errors like this on the website:

  - CPU temperature could not be determined
  - Could not get network data: getIpCommand() failed for eth0
  - Could not get network data: getIpCommand() failed for vethRFEFBS@if5
  - Could not get network data: getIpCommand() failed for vethMPBCOI@if9

veth devices are from LX containers. I see this in my nginx error log:

```
2016/12/13 13:23:40 [error] 15587#15587: *42 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /srv/http/swmp/php/system.php on line 493
PHP message: PHP Notice:  Undefined offset: 0 in /srv/http/swmp/php/system.php on line 494
PHP message: PHP Notice:  Undefined offset: 0 in /srv/http/swmp/php/system.php on line 493
PHP message: PHP Notice:  Undefined offset: 0 in /srv/http/swmp/php/system.php on line 494
PHP message: PHP Notice:  Undefined index: theme in /srv/http/swmp/php/swmp.php on line 78" while reading response header from upstream, client: 192.168.0.10, server: myserver, request: "GET /swmp/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "myserver", referrer: "http://myserver/swmp/"
```

I'm not a PHP dev so I'm not sure how to fix this.

**Comment by fuzzymannerz** [comment]
Just a heads up that I am now working on this and I will release the updated installer script as soon as it's done. I will comment and close this issue once complete.
